### ISSUE TITLE
Modelar una empresa como una clase de Java

### ISSUE THREAD

**Issue by Tulio-Rangel** [Devs-Inc/LibDevsInc#1]
- [x] Es posible crear una instancia de la clase "Empresa"

- [x] Es posible leer y modificar el nombre de la empresa

- [x] Es posible leer y modificar la dirección de la empresa

- [x] Es posible leer y modificar el teléfono de la empresa

- [x] Es posible leer y modificar el NIT de la empresa

**Comment by gabrielhro10** [comment]
Se agregaron atributos, constructor y métodos, a la clase creada en el repositorio.
