### ISSUE TITLE
Modelar el movimiento de dinero como una clase de Java

### ISSUE THREAD

**Issue by Tulio-Rangel** [Devs-Inc/LibDevsInc#3]
- [x] Es posible crear una nueva instancia de la clase "MovimientoDinero"

- [x] Es posible leer y modificar el monto del movimiento

- [x] Es posible crear montos positivos y negativos

- [x] Es posible leer y modificar el concepto del movimiento

- [x] Es posible definir qué usuario fue encargado de registrar el movimiento

**Comment by Tierry88** [comment]
En conjunto con el ingeniero Cristian creamos la clase de acuerdo a requerimiento
